name: Publish to MVN

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Check code formatting
        run: mvn fmt:check

      - name: Publish to Maven Central
        if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, '[release]')
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
          DEVELOPMENT_VERSION=$(echo "$RELEASE_VERSION" | awk -F. -v OFS=. '{$NF+=1; print $0 "-SNAPSHOT"}')
          mvn release:prepare -DreleaseVersion=$RELEASE_VERSION -DdevelopmentVersion=$DEVELOPMENT_VERSION -Darguments="-Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}"
          mvn release:perform -Darguments="-Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}"

      - name: Configure Git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Git Tag
        if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, '[release]')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          git tag $TAG_NAME
          git push origin $TAG_NAME
